#Manage common SpringDoc and OpenAPI related properties

#SpringDoc related properties
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.displayOperationId=true
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=openapi_3_1
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

#OpenAPI 3.1 - Entitlements Service properties
swagger.apiTitle=Entitlements Service
swagger.apiDescription=Entitlements Service is used to enable authorization in OSDU Data Ecosystem
swagger.apiVersion=2.0
swagger.apiContactName=OSDU Data Platform Team
swagger.apiContactEmail=dps@OSDU.org
swagger.apiLicenseName=Apache 2.0
swagger.apiLicenseUrl=https://www.apache.org/licenses/LICENSE-2.0.html
swagger.apiServerUrl=${server.servlet.contextPath:/api/entitlements/v2}
swagger.apiServerFullUrlEnabled=${api.server.fullUrl.enabled:false}

#OpenAPI 3.1 - Entitlements Service properties
addMemberApi.addMember.summary=Add Member
addMemberApi.addMember.description=Add Member

#CreateGroup API related properties
createGroupApi.createGroup.summary=Create Group
createGroupApi.createGroup.description=Create Group

#DeleteGroup API related properties
deleteGroupApi.deleteGroup.summary=Delete Group
deleteGroupApi.deleteGroup.description=Delete Group

#DeleteGroup API related properties
deleteMemberApi.deleteMember.summary=Delete Member
deleteMemberApi.deleteMember.description=Delete Member

#ListGroup API related properties
listGroupApi.listGroups.summary=List Groups
listGroupApi.listGroups.description=List Groups

#ListGroupOnBehalfOf API related properties
listGroupOnBehalfOfApi.listGroupsOnBehalfOf.summary=List Group On Behalf Of
listGroupOnBehalfOfApi.listGroupsOnBehalfOf.description=List Group On Behalf Of
listGroupOnBehalfOfApi.listAllPartitionGroups.summary=List All Partition Groups
listGroupOnBehalfOfApi.listAllPartitionGroups.description=List All Partition Groups

#ListMember API related properties
listMemberApi.listGroupMembers.summary=List Group Members
listMemberApi.listGroupMembers.description=List Group Members

#DeleteGroup API related properties
removeMemberApi.deleteMember.summary=Delete Member
removeMemberApi.deleteMember.description=Delete Member

#UpdateGroup API related properties
updateGroupApi.updateGroup.summary=Update Group
updateGroupApi.updateGroup.description=Update Group

#Init API related properties
initApi.initiateTenant.summary=Initiate Tenant
initApi.initiateTenant.description=Initiate Tenant

#Info & Health API related properties
infoApi.info.summary=Version info
infoApi.info.description=For deployment available public `/info` endpoint, which provides build and git related information.
healthChecksApi.livenessCheck.summary=Liveness Check endpoint
healthChecksApi.livenessCheck.description=For deployment available public `/liveness_check` endpoint.
healthChecksApi.readinessCheck.summary=Readiness Check endpoint
healthChecksApi.readinessCheck.description=For deployment available public `/readiness_check` endpoint.

#MembersCount API related properties
membersCountApi.getMemberCount.summary=Count Members of a group
membersCountApi.getMemberCount.description=Count Members of a group